### ISSUE TITLE
Fix: CMake is required with some gems

### ISSUE THREAD

**Issue by bterone** [nimblehq/laptop#15]
## Issue

![Screen Shot 2020-01-16 at 4 21 37 PM](https://user-images.githubusercontent.com/34730459/72510711-819ef580-387c-11ea-8205-9a6ff2e8e1ca.png)

Some issues arose when trying to setup our project on a new laptop, there's some gem which has the `rugged` dependency which requires CMake to be built
 
## Expected

Should just set up the project without running into issues with bundling.
 
## Steps to reproduce

1. Setup a project with the `rugged` dependency 
2. Use `bundle install`
3. Runs into the error above.

Potential fix might be to `brew install cmake` so that we wouldn't run into this issue 💭

**Comment by olivierobert** [comment]
@bterone Since the error is quite detailed, I am not sure about adding project dependencies in the script as it depends on the gems used 🤔

**Comment by bterone** [comment]
Ah okay, I'll close this then, I thought it was a common thing for gems, since make was provided by default 😅
