### ISSUE TITLE
Add iOS developer specific apps

### ISSUE THREAD

**Issue by edgarss** [nimblehq/laptop#18]
## Needed

- Xcode
- RVM
- cocoapods gem
- figma
- homebrew
- Proxyman
- Atom or some text editor
- iTerm2
- Sourcetree
- go2shell
- Spotify
- chrome
- slack
- Keybase
- 1password

 
## Who Benefits?

iOS chapter

**Comment by suho** [comment]
I think iOS developer will not need these apps from the current list:
- Docker
- Heroku Toolbelt
- Postgres
- Redis
- Tmux (currently, wrong link on README)

I want add more apps for iOS:
- Gifox
- Skitch
- Postman
- Bundler
- NVM
- Ruby
- Zsh
- oh-my-zsh

**Comment by edgarss** [comment]
Gifox isn't free which is why I didn't add it

do we need zsh tho?

**Comment by suho** [comment]
@edgarss I'm using a free version of Gifox and I think it's good enough for us
Also I already configured zsh for my terminal

**Comment by hoangmirs** [comment]
I think these things are personal, but it's fine if you guys need it 😂 
- Sourcetree
- go2shell
- Gifox

**Comment by edgarss** [comment]
@hoangmirs youre probably right
