### ISSUE TITLE
Add Web developer specific apps

### ISSUE THREAD

**Issue by hoangmirs** [nimblehq/laptop#19]
## Needed

- postgres
- redis
- Heroku
- AWS CLI
- Github CLI
- imagemagick
- docker
- yarn
- nvm
 
## Who Benefits?

Web chapter

**Comment by caherrerapa** [comment]
Knowing that all our apps use Docker, does it make sense to add postgres and redis for example?

**Comment by andyduong1920** [comment]
@hoangmirs I think we don't need `Postgres` as we use Docker for it.

How about adding
1/ rvm
2/ elixir
3/ go?
4/ Phrase app cli
5/ AWS CLI

**Comment by hoangmirs** [comment]
I heard that Omise didn't use Docker, I'm not sure for now
But I also prefer to remove it

**Comment by olivierobert** [comment]
Some clients indeed do not use Docker so I recommend to keep Postgres via brew services. Redis could be removed.

@anduonghien RVM and NVM are already installed by default.
