### ISSUE TITLE
Fix: nvm script not being added to .zshrc file

### ISSUE THREAD

**Issue by Jedmed** [nimblehq/laptop#25]
## Issue

After running setup script and reaching the end of the installation, I was not able to run nvm in terminal. After checking my zshrc file, I notice that the nvm config was missing.  I suspect that because the config is set before `oh my zsh` installation, the config file gets overridden.
 
## Expected

After installation, the nvm config should be in the zshrc file.

## Steps to reproduce

1. Run install script, select web dependencies and select install zsh extensions
2. Open ~/.zshrc file 
3. Check if file has nvm config code

**Comment by olivierobert** [comment]
Fixed by #26
