### ISSUE TITLE
Remove postgres

### ISSUE THREAD

**Issue by malparty** [nimblehq/laptop#39]
## Why

This issue is to discuss if this is possible or not. 

We got the case that a fresh setup with a local Postgres instance was conflicting with the Postgres container of the client project (port/IP). 
For new members, it can be quite "implicit" and hard to debug. 

Should we remove Postgres from this script and consider it as a "project dependency" instead of as a "development tool"? 🤔 
 
## Who Benefits?

Developers can reduce the risks of DB port conflicts.

**Comment by hoangmirs** [comment]
We don't need the Postgres installed on the machine. I think the reason for it is to resolve the following error when running a Rails project:
![Welcome_—_nimble-survey-web](https://github.com/nimblehq/laptop/assets/7344405/5080b624-b0e7-4c21-b997-5e620a20a5f1)

We might just need the following commands to install the `pg` gem:
```
brew install libpq
echo 'export PATH="/opt/homebrew/opt/libpq/bin:$PATH"' >> ~/.zshrc
```

I tested, and it worked 🎉 
![Welcome_—_nimble-survey-web](https://github.com/nimblehq/laptop/assets/7344405/353bda96-e303-4abc-88f6-8df68bf1de4e)

**Comment by tyrro** [comment]
@hoangmirs , I tried removing postgres from my local machine as you suggested and it worked, Thanks 🎉 
I just had to make sure I opened a new iTerm window after adding `PATH` to `.zshrc`.

**Comment by malparty** [comment]
> I just had to make sure I opened a new iTerm window after adding PATH to .zshrc

The command to reload without restarting the terminal session is `source ~/.zshrc` ;-)


@hoangmirs / @tyrro let's apporove & merge your PR #40 🚀
